import type { Metadata } from 'next';
import { Outfit } from 'next/font/google';
import './globals.css';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import { ThemeProvider } from '@/components/ThemeProvider';
import ClientOnly from '@/components/ClientOnly';
import { Toaster } from '@/components/ui/toaster';

const outfit = Outfit({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Joben Apao | Frontend Developer',
	description: 'Generated by create next app',
	icons: {
		icon: '/images/logo-dark.png',
	},
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang='en'
			suppressHydrationWarning
		>
			<body className={outfit.className}>
				<ClientOnly>
					<ThemeProvider
						attribute='class'
						defaultTheme='dark'
					>
						<Header />
						{children}

						<Footer />
						<Toaster />
					</ThemeProvider>
				</ClientOnly>
			</body>
		</html>
	);
}
